name: cmake-py # you probably want to 'snapcraft register <name>'
version: '0.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: "toy snap to understand cmake with behavior in snapcraft."
description: |
  "little to say, it's just a toy."

grade: devel
confinement: devmode

parts:
  caller:
    source: ..
    plugin: cmake

  pylib:
    source: ../src/mylibrary
    plugin: python
    python-packages: [setuptools]
    # setuptools is not installed on vm:
    # ImportError: No module named 'pkg_resources'
    
  en:
    after: [pylib]
    source: ../src/english
    plugin: python

  es:
    after: [pylib]
    source: ../src/spanish
    plugin: python    

  zh:
    after: [pylib]
    source: ../src/chinese
    plugin: python

apps:
  caller:
    command: roll_call
