name: cmake-py # you probably want to 'snapcraft register <name>'
version: '0.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: "toy snap to understand cmake with behavior in snapcraft."
description: |
  "little to say, it's just a toy."

parts:
  everything:
    source: ..
    plugin: cmake

